version: '3'
services:
  app:
    image: laravel-app-image
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - 'DB_CONNECTION=mysql'
      - 'DB_HOST=192.241.155.75'
      - 'DB_PORT=3306'
      - 'DB_DATABASE=trading_acco'
      - 'DB_USERNAME=trading_acco'
      - 'DB_PASSWORD=RekUC9SOZ0bClyl7'
    ports:
      - 80:8000
